export const projectId = "jytjdryjgcxgnfwlgtwc";
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5dGpkcnlqZ2N4Z25md2xndHdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2MDYwMjQsImV4cCI6MjA4NDE4MjAyNH0.lLWFWMIrLm0GzPAF3vFRAUfKaFkCMkxIXsXN8P5z-vU";
